m4105_smithe/src/s4smithe/VitrineBundle/Entity/Commande.php
<?php

	/*
	 * Fichier : Commande.php
	 * Auteur: SMITH Emmanuel
	 * Création: 19/03/2016
	 * Modification: 22/03/2016
	 *
	 * Entitée Commande
	 */

	namespace s4smithe\VitrineBundle\Entity;

	use Doctrine\Common\Collections\ArrayCollection;

	/**
	 * Commande
	 */
	class Commande {

		/**
		 * @var integer
		 */
		private $id;

		/**
		 * @var \DateTime
		 */
		private $date;

		/**
		 * @var boolean
		 */
		private $etat = false;

		/**
		 * @var \s4smithe\VitrineBundle\Entity\Client
		 */
		private $client;

		/**
		 * Commande constructor.
		 *
		 * @param Client $client
		 */
		public function __construct( \s4smithe\VitrineBundle\Entity\Client $client = null ) {
			$this->lignesommandes = new ArrayCollection();
			$this->setDate( new \DateTime() );
			$this->setClient( $client );
		}


		/**
		 * Get id
		 *
		 * @return integer
		 */
		public function getId() {
			return $this->id;
		}

		/**
		 * Set date
		 *
		 * @param \DateTime $date
		 *
		 * @return Commande
		 */
		public function setDate( $date ) {
			$this->date = $date;

			return $this;
		}

		/**
		 * Get date
		 *
		 * @return \DateTime
		 */
		public function getDate() {
			return $this->date;
		}

		/**
		 * Set etat
		 *
		 * @param boolean $etat
		 *
		 * @return Commande
		 */
		public function setEtat( $etat ) {
			$this->etat = $etat;

			return $this;
		}

		/**
		 * Get etat
		 *
		 * @return boolean
		 */
		public function getEtat() {
			return $this->etat;
		}

		/**
		 * Set client
		 *
		 * @param \s4smithe\VitrineBundle\Entity\Client $client
		 *
		 * @return Commande
		 */
		public function setClient( \s4smithe\VitrineBundle\Entity\Client $client = null ) {
			$this->client = $client;

			return $this;
		}

		/**
		 * Get client
		 *
		 * @return \s4smithe\VitrineBundle\Entity\Client
		 */
		public function getClient() {
			return $this->client;
		}

		/**
		 * @var \Doctrine\Common\Collections\Collection
		 */
		private $lignecommandes;


		/**
		 * Add lignecommandes
		 *
		 * @param \s4smithe\VitrineBundle\Entity\LigneCommande $lignecommandes
		 *
		 * @return Commande
		 */
		public function addLignecommande( \s4smithe\VitrineBundle\Entity\LigneCommande $lignecommandes ) {
			$this->lignecommandes[] = $lignecommandes;

			return $this;
		}

		/**
		 * Remove lignecommandes
		 *
		 * @param \s4smithe\VitrineBundle\Entity\LigneCommande $lignecommandes
		 */
		public function removeLignecommande( \s4smithe\VitrineBundle\Entity\LigneCommande $lignecommandes ) {
			$this->lignecommandes->removeElement( $lignecommandes );
		}

		/**
		 * Get lignecommandes
		 *
		 * @return \Doctrine\Common\Collections\Collection
		 */
		public function getLignecommandes() {
			return $this->lignecommandes;
		}


		/**
		 * @return int
		 */
		public function getPrixCommande() {
			$total = 0;

			foreach ( $this->getLignecommandes() as $ligne ) {
				$total += $ligne->getPrix() * $ligne->getQte();
			}

			return $total;
		}

		/**
		 * @return int
		 */
		public function getNbArticleCommande() {
			$nb = 0;

			foreach ( $this->getLignecommandes() as $ligne ) {
				$nb += $ligne->getQte();
			}

			return $nb;
		}

	}

m4105_smithe/src/s4smithe/VitrineBundle/Form/CommandeType.php
<?php

namespace s4smithe\VitrineBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommandeType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date', 'datetime')
            ->add('etat')
            ->add('client')
        ;
    }
    
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 's4smithe\VitrineBundle\Entity\Commande'
        ));
    }
}

m4105_smithe/src/s4smithe/VitrineBundle/Form/Type/CommandeType.php
<?php

	/*
	 * Fichier : CommandeType.php
	 * Auteur: SMITH Emmanuel
	 * Création: 08/03/2016
	 * Modification: 22/03/2016
	 *
	 * Form builder pour l'entitée Commande.
	 */

	namespace s4smithe\VitrineBundle\Form\Type;

	use Symfony\Component\Form\AbstractType;
	use Symfony\Component\Form\FormBuilderInterface;
	use Symfony\Component\OptionsResolver\OptionsResolver;

	/**
	 * Class CommandeType
	 *
	 * @package s4smithe\VitrineBundle\Form\Type
	 */
	class CommandeType extends AbstractType {
		/**
		 * @param FormBuilderInterface $builder
		 * @param array                $options
		 */
		public function buildForm( FormBuilderInterface $builder, array $options ) {
			$builder
				->add( 'date', 'datetime' )
				->add( 'etat' )
				->add( 'client' );
		}

		/**
		 * @param OptionsResolver $resolver
		 */
		public function configureOptions( OptionsResolver $resolver ) {
			$resolver->setDefaults(
				array(
					'data_class' => 's4smithe\VitrineBundle\Entity\Commande'
				)
			);
		}
	}

m4105_smithe/src/s4smithe/VitrineBundle/Controller/CommandeController.php
<?php


	/*
	 * Fichier : CommandeController.php
	 * Auteur: SMITH Emmanuel
	 * Création: 19/03/2016
	 * Modification: 22/03/2016
	 *
	 * Controôleur pour la gestion des entitiés Commandes
	 */

	namespace s4smithe\VitrineBundle\Controller;

	use s4smithe\VitrineBundle\Entity\Commande;
	use Symfony\Bundle\FrameworkBundle\Controller\Controller;
	use Symfony\Component\HttpFoundation\Request;

	/**
	 * Commande controller.
	 *
	 */
	class CommandeController extends Controller {

		/**
		 * Lists all Commande entities.
		 *
		 */
		public function indexAction() {
			$em = $this->getDoctrine()->getManager();

			$commandes = $em->getRepository( 's4smitheVitrineBundle:Commande' )->findAll();

			return $this->render(
				's4smitheVitrineBundle:Commande:index.html.twig', array(
					'commandes' => $commandes,
				)
			);
		}

		/**
		 * Creates a new Commande entity.
		 *
		 */
		public function newAction( Request $request ) {
			$commande = new Commande();

			$form = $this->createForm( 's4smithe\VitrineBundle\Form\Type\CommandeType', $commande );
			$form->handleRequest( $request );

			if ( $form->isSubmitted() && $form->isValid() ) {
				$em = $this->getDoctrine()->getManager();
				$em->persist( $commande );
				$em->flush();

				return $this->redirectToRoute( 'commande_show', array( 'id' => $commande->getId() ) );
			}

			return $this->render(
				'commande/new.html.twig', array(
					'commande' => $commande,
					'form'     => $form->createView(),
				)
			);
		}

		/**
		 * Finds and displays a Commande entity.
		 *
		 */
		public function showAction( Commande $commande ) {
			$deleteForm = $this->createDeleteForm( $commande );

			return $this->render(
				's4smitheVitrineBundle:Commande:show.html.twig', array(
					'commande'    => $commande,
					'delete_form' => $deleteForm->createView(),
				)
			);
		}

		/**
		 * @param Commande $commande
		 *
		 * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
		 */
		public function detailAction( Commande $commande ) {
			if ( $commande->getClient()->getId() !== $this->getSessionUser() ) {
				return $this->redirectToRoute( "s4smithe_vitrine_homepage" );
			}

			return $this->showAction( $commande );
		}

		/**
		 * Displays a form to edit an existing Commande entity.
		 *
		 */
		public function editAction( Request $request, Commande $commande ) {


			$editForm = $this->createFormBuilder( $commande )
				->add( 'date', 'datetime', array( 'disabled' => true ) )
				->add( 'etat' )
				->add( 'client', null, array( 'disabled' => true ) )
				->getForm();

			$editForm->handleRequest( $request );

			if ( $editForm->isSubmitted() && $editForm->isValid() ) {
				$em = $this->getDoctrine()->getManager();
				$em->persist( $commande );
				$em->flush();

				$message = array(
					'type'    => 'success',
					'title'   => "Commande modifié",
					'message' => 'La commande à bien été modifiée'
				);

				$this->getRequest()->getSession()->getFlashBag()->add( 'message', $message );

				return $this->redirectToRoute( 'commande_edit', array( 'id' => $commande->getId() ) );
			}

			return $this->render(
				's4smitheVitrineBundle:Commande:edit.html.twig', array(
					'commande'    => $commande,
					'edit_form'   => $editForm->createView(),
				)
			);
		}

		/**
		 * Deletes a Commande entity.
		 *
		 */
		public function deleteAction( Request $request, Commande $commande ) {
			$form = $this->createDeleteForm( $commande );
			$form->handleRequest( $request );

			if ( $form->isSubmitted() && $form->isValid() ) {
				$em = $this->getDoctrine()->getManager();
				$em->remove( $commande );
				$em->flush();
			}

			return $this->redirectToRoute( 'client_listCommande' );
		}

		/**
		 * Creates a form to delete a Commande entity.
		 *
		 * @param Commande $commande The Commande entity
		 *
		 * @return \Symfony\Component\Form\Form The form
		 */
		private function createDeleteForm( Commande $commande ) {
			return $this->createFormBuilder()
				->setAction(
					$this->generateUrl( 'commande_delete', array( 'id' => $commande->getId() ) )
				)
				->setMethod( 'DELETE' )
				->getForm();
		}


		/**
		 * @return int
		 */
		private function getSessionUser() {
			$session = $this->getRequest()->getSession();

			return $session->get( 'userId', -1 );
		}

	}

m4105_smithe/src/s4smithe/VitrineBundle/Resources/views/Commande/edit.html.twig
{#

	  Fichier : /Commande/edit.html.twig
	  Auteur: SMITH Emmanuel
	  Création: 19/03/2016
	  Modification: 01/04/16

	  Vue CRUD - Edition d'une commande

#}

{% set namePage = "Commande n°" ~ commande.id %}
{% set typePage = namePage %}
{% extends "s4smitheVitrineBundle::layoutBackOffice.html.twig" %}

{% block linkFollowing %}
	<li class="active" >Commande</li >
	<li >N°{{ commande.id }}</li >
	<li >Edition</li >
{% endblock %}

{% block content %}
	<div class="col-xs-12" >
		{% for flashMessage in app.session.flashbag.get('message') %}
			{% include "s4smitheVitrineBundle:Default:flashMessage.html.twig" %}
		{% endfor %}

		{{ form_start(edit_form) }}
		{{ form_widget(edit_form) }}
		<button type="reset" title="Annuler" class="btn btn-sm btn-default" >Annuler</button >
		<button type="submit" title="Editer" class="btn btn-sm btn-primary" >Editier</button >
		{{ form_end(edit_form) }}

		<a href="{{ path('commande_index') }}" title="Retour à la liste" class="btn btn-sm btn-default" >Retour</a >
	</div >
{% endblock %}

m4105_smithe/src/s4smithe/VitrineBundle/Resources/views/Commande/index.html.twig
{#

	  Fichier : /Commande/index.html.twig
	  Auteur: SMITH Emmanuel
	  Création: 19/03/2016
	  Modification: 01/04/16

	  Vue CRUD - Liste de l'ensemble des commandes non détailé

#}

{% set namePage = "Listes des commandes" %}
{% set typePage = namePage %}
{% extends "s4smitheVitrineBundle::layoutBackOffice.html.twig" %}

{% block linkFollowing %}
	<li class="active" >{{ namePage }}</li >
{% endblock %}

{% block content %}

	<div class="col-xs-12" >
		<table class="table table-responsive tableCustum" >

			<tr >
				<th >Commande</th ><!--  Date + Client -->
				<th class="text-center qte" >ID</th >
				<th class="text-center littleTD" >Etat</th >
				<th class="text-center littleTD" >Prix TTC</th >
				<th class="actionItem" ></th >
			</tr >

			{% if commandes|length > 0 %}
				{% set totalCommande = 0 %}
				{% for commande in commandes %}
					{% set totalCommande = totalCommande + commande.PrixCommande %}
					<tr >
						<td >
							<div class="col-md-12" >{{ commande.client.name }}</div >
							<div class="col-md-12" >
								<span class="subInfoPanier" >{{ commande.date|date('Y-m-d H:i:s') }}</span >
							</div >
						</td >
						<td class="text-center" >{{ commande.id }}</td >
						<td class="text-center" >{% if commande.etat %}Validé{% else %}En Attente{% endif %}</td >
						<td class="text-center" >{{ commande.PrixCommande|number_format(2, ',', ' ') }} €</td >
						<td class="text-center actionItem" >
							<a href="{{ path('commande_edit', { 'id': commande.id }) }}" class="badge badge-blue" title="Editer" ><span class="fa fa-pencil" ></span ></a >
						</td >
					</tr >
				{% endfor %}
				<tr >
					<td colspan="5" >
						<span class="text-small" >{{ commandes|length }} commande(s)</span >
					</td >
				</tr >
			{% else %}
				<tr >
					<td colspan="5" > Pas de commandes encore enregistrés</td >
				</tr >
			{% endif %}
		</table >
	</div >

{% endblock %}

m4105_smithe/src/s4smithe/VitrineBundle/Resources/views/Commande/show.html.twig
{#

	  Fichier : /Commande/show.html.twig
	  Auteur: SMITH Emmanuel
	  Création: 19/03/2016
	  Modification: 01/04/16

	  Vue CRUD - Affiche la commande détailé

#}

{% set namePage = "Détail commande n°" ~ commande.id %}
{% set typePage = namePage %}
{% extends "s4smitheVitrineBundle::layout.html.twig" %}

{% block titlePage %}
	{{ parent() }}
	{{ form_start(delete_form, { 'attr': {'class': 'form-inline visible-lg-inline'} }) }}
	<button type="submit" title="Annuler la commande" class="btn btn-primary btn-sm" >Annuler</button >
	{{ form_end(delete_form) }}
{% endblock %}

{% block linkFollowing %}
	<li class="active" >Categorie</li >
{% endblock %}

{% block content %}
	<div class="col-xs-12" >
		<table class="table table-responsive tableCustum" >
			<tr >
				<th >Commande</th ><!--  Date + Client -->
				<th class="text-center qte" >ID</th >
				<th class="text-center littleTD" >Etat</th >
			</tr >
			<tr >
				<td >
					<div class="col-xs-12" >
						{{ commande.client.name }}
					</div >
					<div class="col-md-12" >
						<span class="subInfoPanier" >{{ commande.date|date('Y-m-d H:i:s') }}</span >
					</div >
				</td >
				<td class="text-center" >{{ commande.id }}</td >
				<td class="text-center" >{% if commande.etat %}Validé{% else %}En Attente{% endif %}</td >
			</tr >
		</table >


		<table class="table table-responsive tableCustum" >
			<tr >
				<th >Article</th >
				<th class="text-center qte" >Qté</th >
				<th class="text-center littleTD" >Prix U. TTC</th >
				<th class="text-center littleTD" >Total TTC</th >
			</tr >

			{% if commande.lignecommandes|length > 0 %}
				{% for item in commande.lignecommandes %}
					<tr >
						<td >
							<div class="col-md-12" >{{ item.product.name }}</div >
							<div class="col-md-12" >
								<span class="subInfoPanier" >{{ item.product.category.name }}</span >
								<span class="subInfoPanier" >- {{ item.product.marque.name }}</span >
							</div >
						</td >
						<td class="text-center" ><span class="badge badge-blue" >x {{ item.qte }}</span ></td >
						<td class="text-center" >{{ item.product.price|number_format(2, ',', ' ') }} €</td >
						<td class="text-center" >{{ (item.qte * item.product.price)|number_format(2, ',', ' ') }} €</td >
					</tr >
				{% endfor %}
				<tr >
					<td >
						<span class="text-small" >{{ commande.nbArticleCommande }} article(s) dans la commande</span >
					</td >
					<td colspan="2" class="text-right" style="font-variant: small-caps;" >Total de la Commande</td >
					<td class="text-center total" >{{ commande.prixCommande|number_format(2, ',', ' ') }} €</td >
				</tr >
			{% endif %}

		</table >


		<a href="{{ path('client_listCommande') }}" title="Retour à la liste" class="btn btn-default" >Retour</a >
	</div >
{% endblock %}